const allPlayers = [
  {
    "id": "3149391",
    "name": "A'ja Wilson",
    "team": "Las Vegas Aces",
    "position": "C",
    "jersey": "22",
    "age": 30,
    "height": "6' 4\"",
    "college": "South Carolina",
    "birthPlace": "Hopkins, SC, USA",
    "experience": 9,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/3149391/aja-wilson",
    "ppg": 26.0,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/3149391.png"
  },
  {
    "id": "3142191",
    "name": "Kelsey Mitchell",
    "team": "Indiana Fever",
    "position": "G",
    "jersey": "0",
    "age": 30,
    "height": "5' 8\"",
    "college": "Ohio State",
    "birthPlace": "Cincinnati, OH, USA",
    "experience": 9,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/3142191/kelsey-mitchell",
    "ppg": 25.0,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/3142191.png"
  },
  {
    "id": "4433403",
    "name": "Caitlin Clark",
    "team": "Indiana Fever",
    "position": "G",
    "jersey": "22",
    "age": 24,
    "height": "6' 0\"",
    "college": "Iowa",
    "birthPlace": "West Des Moines, IA, USA",
    "experience": 3,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/4433403/caitlin-clark",
    "ppg": 22.5,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/4433403.png"
  },
  {
    "id": "2998938",
    "name": "Kahleah Copper",
    "team": "Phoenix Mercury",
    "position": "G",
    "jersey": "2",
    "age": 32,
    "height": "6' 1\"",
    "college": "Rutgers",
    "birthPlace": "Philadelphia, PA, USA",
    "experience": 11,
    "status": "Out",
    "profile": "https://www.espn.com/wnba/player/_/id/2998938/kahleah-copper",
    "ppg": 21.3,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/2998938.png"
  },
  {
    "id": "3904576",
    "name": "Marina Mabrey",
    "team": "Toronto Tempo",
    "position": "G",
    "jersey": "3",
    "age": 29,
    "height": "6' 1\"",
    "college": "Notre Dame",
    "birthPlace": "Belmar, NJ, USA",
    "experience": 8,
    "status": "Out",
    "profile": "https://www.espn.com/wnba/player/_/id/3904576/marina-mabrey",
    "ppg": 20.8,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/3904576.png"
  },
  {
    "id": "4433730",
    "name": "Paige Bueckers",
    "team": "Dallas Wings",
    "position": "G",
    "jersey": "5",
    "age": 24,
    "height": "6' 0\"",
    "college": "UConn",
    "birthPlace": "Hopkins, MN, USA",
    "experience": 2,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/4433730/paige-bueckers",
    "ppg": 20.5,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/4433730.png"
  },
  {
    "id": "2998928",
    "name": "Breanna Stewart",
    "team": "New York Liberty",
    "position": "F",
    "jersey": "30",
    "age": 32,
    "height": "6' 4\"",
    "college": "UConn",
    "birthPlace": "North Syracuse, NY, USA",
    "experience": 10,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/2998928/breanna-stewart",
    "ppg": 20.4,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/2998928.png"
  },
  {
    "id": "4433791",
    "name": "Olivia Miles",
    "team": "Minnesota Lynx",
    "position": "G",
    "jersey": "5",
    "age": 23,
    "height": "5' 10\"",
    "college": "TCU",
    "birthPlace": "Phillipsburg, NJ, USA",
    "experience": 0,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/4433791/olivia-miles",
    "ppg": 19.7,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/4433791.png"
  },
  {
    "id": "3058901",
    "name": "Allisha Gray",
    "team": "Atlanta Dream",
    "position": "G",
    "jersey": "15",
    "age": 31,
    "height": "6' 0\"",
    "college": "South Carolina",
    "birthPlace": "Greenwood, SC, USA",
    "experience": 10,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/3058901/allisha-gray",
    "ppg": 19.3,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/3058901.png"
  },
  {
    "id": "4065870",
    "name": "Jackie Young",
    "team": "Las Vegas Aces",
    "position": "G",
    "jersey": "0",
    "age": 28,
    "height": "6' 0\"",
    "college": "Notre Dame",
    "birthPlace": "Princeton, IN, USA",
    "experience": 8,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/4065870/jackie-young",
    "ppg": 18.9,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/4065870.png"
  },
  {
    "id": "4398674",
    "name": "Rhyne Howard",
    "team": "Atlanta Dream",
    "position": "G",
    "jersey": "10",
    "age": 26,
    "height": "6' 2\"",
    "college": "Kentucky",
    "birthPlace": "Chattanooga, TN, USA",
    "experience": 5,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/4398674/rhyne-howard",
    "ppg": 18.3,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/4398674.png"
  },
  {
    "id": "2529205",
    "name": "Kayla McBride",
    "team": "Minnesota Lynx",
    "position": "G",
    "jersey": "21",
    "age": 34,
    "height": "5' 11\"",
    "college": "Notre Dame",
    "birthPlace": "Erie, PA, USA",
    "experience": 13,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/2529205/kayla-mcbride",
    "ppg": 18.1,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/2529205.png"
  },
  {
    "id": "1068",
    "name": "Nneka Ogwumike",
    "team": "Los Angeles Sparks",
    "position": "F",
    "jersey": "30",
    "age": 36,
    "height": "6' 2\"",
    "college": "Stanford",
    "birthPlace": "Tomball, TX, USA",
    "experience": 15,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/1068/nneka-ogwumike",
    "ppg": 17.2,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/1068.png"
  },
  {
    "id": "5220150",
    "name": "Dominique Malonga",
    "team": "Seattle Storm",
    "position": "C",
    "jersey": "14",
    "age": 20,
    "height": "6' 6\"",
    "college": "",
    "birthPlace": "",
    "experience": 2,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/5220150/dominique-malonga",
    "ppg": 17.0,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/5220150.png"
  },
  {
    "id": "4432831",
    "name": "Aliyah Boston",
    "team": "Indiana Fever",
    "position": "C",
    "jersey": "7",
    "age": 24,
    "height": "6' 5\"",
    "college": "South Carolina",
    "birthPlace": "St. Thomas, Virgin Islands",
    "experience": 4,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/4432831/aliyah-boston",
    "ppg": 16.9,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/4432831.png"
  },
  {
    "id": "4398911",
    "name": "Shakira Austin",
    "team": "Washington Mystics",
    "position": "C",
    "jersey": "0",
    "age": 26,
    "height": "6' 5\"",
    "college": "Ole Miss",
    "birthPlace": "Fredericksburg, VA, USA",
    "experience": 5,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/4398911/shakira-austin",
    "ppg": 16.8,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/4398911.png"
  },
  {
    "id": "4433524",
    "name": "Sonia Citron",
    "team": "Washington Mystics",
    "position": "G",
    "jersey": "22",
    "age": 22,
    "height": "6' 1\"",
    "college": "Notre Dame",
    "birthPlace": "Eastchester, NY, USA",
    "experience": 2,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/4433524/sonia-citron",
    "ppg": 16.8,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/4433524.png"
  },
  {
    "id": "4433402",
    "name": "Angel Reese",
    "team": "Atlanta Dream",
    "position": "F",
    "jersey": "5",
    "age": 24,
    "height": "6' 4\"",
    "college": "LSU",
    "birthPlace": "Baltimore, MD, USA",
    "experience": 3,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/4433402/angel-reese",
    "ppg": 16.1,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/4433402.png"
  },
  {
    "id": "5208982",
    "name": "Carla Leite",
    "team": "Portland Fire",
    "position": "G",
    "jersey": "0",
    "age": 22,
    "height": "5' 9\"",
    "college": "",
    "birthPlace": "",
    "experience": 2,
    "status": "Out",
    "profile": "https://www.espn.com/wnba/player/_/id/5208982/carla-leite",
    "ppg": 15.9,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/5208982.png"
  },
  {
    "id": "3906753",
    "name": "Natisha Hiedeman",
    "team": "Seattle Storm",
    "position": "G",
    "jersey": "2",
    "age": 29,
    "height": "5' 8\"",
    "college": "Marquette",
    "birthPlace": "Green Bay, WI, USA",
    "experience": 8,
    "status": "Out",
    "profile": "https://www.espn.com/wnba/player/_/id/3906753/natisha-hiedeman",
    "ppg": 15.4,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/3906753.png"
  },
  {
    "id": "4898384",
    "name": "Kiki Iriafen",
    "team": "Washington Mystics",
    "position": "F",
    "jersey": "44",
    "age": 23,
    "height": "6' 3\"",
    "college": "USC",
    "birthPlace": "Los Angeles, CA, USA",
    "experience": 2,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/4898384/kiki-iriafen",
    "ppg": 15.3,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/4898384.png"
  },
  {
    "id": "3904577",
    "name": "Arike Ogunbowale",
    "team": "Dallas Wings",
    "position": "G",
    "jersey": "24",
    "age": 29,
    "height": "5' 8\"",
    "college": "Notre Dame",
    "birthPlace": "Milwaukee, WI, USA",
    "experience": 8,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/3904577/arike-ogunbowale",
    "ppg": 15.2,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/3904577.png"
  },
  {
    "id": "2529130",
    "name": "Natasha Howard",
    "team": "Minnesota Lynx",
    "position": "F",
    "jersey": "1",
    "age": 35,
    "height": "6' 2\"",
    "college": "Florida State",
    "birthPlace": "",
    "experience": 13,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/2529130/natasha-howard",
    "ppg": 14.9,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/2529130.png"
  },
  {
    "id": "4433405",
    "name": "Kamilla Cardoso",
    "team": "Chicago Sky",
    "position": "C",
    "jersey": "10",
    "age": 25,
    "height": "6' 7\"",
    "college": "South Carolina",
    "birthPlace": "Montes Claros, Brazil",
    "experience": 3,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/4433405/kamilla-cardoso",
    "ppg": 14.8,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/4433405.png"
  },
  {
    "id": "4398764",
    "name": "Rae Burrell",
    "team": "Los Angeles Sparks",
    "position": "G",
    "jersey": "12",
    "age": 26,
    "height": "6' 2\"",
    "college": "Tennessee",
    "birthPlace": "Las Vegas, NV, USA",
    "experience": 5,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/4398764/rae-burrell",
    "ppg": 14.6,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/4398764.png"
  },
  {
    "id": "2999101",
    "name": "Jonquel Jones",
    "team": "New York Liberty",
    "position": "C",
    "jersey": "35",
    "age": 32,
    "height": "6' 6\"",
    "college": "George Washington",
    "birthPlace": "Freeport, GB, Bahamas",
    "experience": 10,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/2999101/jonquel-jones",
    "ppg": 14.6,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/2999101.png"
  },
  {
    "id": "3906949",
    "name": "Jessica Shepard",
    "team": "Dallas Wings",
    "position": "F",
    "jersey": "32",
    "age": 29,
    "height": "6' 4\"",
    "college": "Notre Dame",
    "birthPlace": "Fremont, NE, USA",
    "experience": 6,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/3906949/jessica-shepard",
    "ppg": 14.4,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/3906949.png"
  },
  {
    "id": "2566106",
    "name": "Dearica Hamby",
    "team": "Los Angeles Sparks",
    "position": "F",
    "jersey": "5",
    "age": 32,
    "height": "6' 3\"",
    "college": "Wake Forest",
    "birthPlace": "Marietta, GA, USA",
    "experience": 12,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/2566106/dearica-hamby",
    "ppg": 14.4,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/2566106.png"
  },
  {
    "id": "3142328",
    "name": "Gabby Williams",
    "team": "Golden State Valkyries",
    "position": "F",
    "jersey": "1",
    "age": 29,
    "height": "5' 11\"",
    "college": "UConn",
    "birthPlace": "Sparks, NV, USA",
    "experience": 8,
    "status": "Out",
    "profile": "https://www.espn.com/wnba/player/_/id/3142328/gabby-williams",
    "ppg": 14.3,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/3142328.png"
  },
  {
    "id": "2987891",
    "name": "Courtney Williams",
    "team": "Minnesota Lynx",
    "position": "G",
    "jersey": "10",
    "age": 32,
    "height": "5' 8\"",
    "college": "South Florida",
    "birthPlace": "Folkston, GA, USA",
    "experience": 11,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/2987891/courtney-williams",
    "ppg": 14.3,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/2987891.png"
  },
  {
    "id": "3906972",
    "name": "Bridget Carleton",
    "team": "Portland Fire",
    "position": "F",
    "jersey": "6",
    "age": 29,
    "height": "6' 2\"",
    "college": "Iowa State",
    "birthPlace": "Chatham, ON, Canada",
    "experience": 8,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/3906972/bridget-carleton",
    "ppg": 14.3,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/3906972.png"
  },
  {
    "id": "2529140",
    "name": "Alyssa Thomas",
    "team": "Phoenix Mercury",
    "position": "F",
    "jersey": "25",
    "age": 34,
    "height": "6' 2\"",
    "college": "Maryland",
    "birthPlace": "Camp Hill, PA, USA",
    "experience": 13,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/2529140/alyssa-thomas",
    "ppg": 14.2,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/2529140.png"
  },
  {
    "id": "4698736",
    "name": "Flau'jae Johnson",
    "team": "Seattle Storm",
    "position": "G",
    "jersey": "4",
    "age": 22,
    "height": "5' 10\"",
    "college": "LSU",
    "birthPlace": "Savannah, GA, USA",
    "experience": 0,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/4698736/flaujae-johnson",
    "ppg": 14.1,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/4698736.png"
  },
  {
    "id": "4594786",
    "name": "Sydney Taylor",
    "team": "Chicago Sky",
    "position": "G",
    "jersey": "12",
    "age": 25,
    "height": "5' 9\"",
    "college": "Louisville",
    "birthPlace": "Long Island, NY, USA",
    "experience": 0,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/4594786/sydney-taylor",
    "ppg": 13.8,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/4594786.png"
  },
  {
    "id": "3934218",
    "name": "Megan DiLeo",
    "team": "Portland Fire",
    "position": "C",
    "jersey": "17",
    "age": 29,
    "height": "6' 4\"",
    "college": "Iowa",
    "birthPlace": "Port Wing, WI, USA",
    "experience": 8,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/3934218/megan-dileo",
    "ppg": 13.2,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/3934218.png"
  },
  {
    "id": "4433790",
    "name": "Azzi Fudd",
    "team": "Dallas Wings",
    "position": "G",
    "jersey": "35",
    "age": 23,
    "height": "5' 11\"",
    "college": "UConn",
    "birthPlace": "Arlington, VA, USA",
    "experience": 0,
    "status": "Out",
    "profile": "https://www.espn.com/wnba/player/_/id/4433790/azzi-fudd",
    "ppg": 13.1,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/4433790.png"
  },
  {
    "id": "4790264",
    "name": "Janelle Salaun",
    "team": "Golden State Valkyries",
    "position": "F",
    "jersey": "13",
    "age": 24,
    "height": "6' 2\"",
    "college": "",
    "birthPlace": "",
    "experience": 2,
    "status": "Out",
    "profile": "https://www.espn.com/wnba/player/_/id/4790264/janelle-salaun",
    "ppg": 12.9,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/4790264.png"
  },
  {
    "id": "2566453",
    "name": "Isabelle Harrison",
    "team": "Toronto Tempo",
    "position": "F",
    "jersey": "21",
    "age": 32,
    "height": "6' 5\"",
    "college": "Tennessee",
    "birthPlace": "Nashville, TN, USA",
    "experience": 9,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/2566453/isabelle-harrison",
    "ppg": 12.4,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/2566453.png"
  },
  {
    "id": "4398935",
    "name": "Veronica Burton",
    "team": "Golden State Valkyries",
    "position": "G",
    "jersey": "22",
    "age": 26,
    "height": "5' 9\"",
    "college": "Northwestern",
    "birthPlace": "Newton, MA, USA",
    "experience": 5,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/4398935/veronica-burton",
    "ppg": 12.3,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/4398935.png"
  },
  {
    "id": "2529122",
    "name": "Chelsea Gray",
    "team": "Las Vegas Aces",
    "position": "G",
    "jersey": "12",
    "age": 33,
    "height": "5' 11\"",
    "college": "Duke",
    "birthPlace": "Hayward, CA, USA",
    "experience": 12,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/2529122/chelsea-gray",
    "ppg": 12.0,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/2529122.png"
  },
  {
    "id": "4398776",
    "name": "NaLyssa Smith",
    "team": "Las Vegas Aces",
    "position": "F",
    "jersey": "3",
    "age": 26,
    "height": "6' 4\"",
    "college": "Baylor",
    "birthPlace": "Converse, TX, USA",
    "experience": 5,
    "status": "Out",
    "profile": "https://www.espn.com/wnba/player/_/id/4398776/nalyssa-smith",
    "ppg": 11.7,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/4398776.png"
  },
  {
    "id": "3142250",
    "name": "Jordin Canada",
    "team": "Atlanta Dream",
    "position": "G",
    "jersey": "3",
    "age": 31,
    "height": "5' 6\"",
    "college": "UCLA",
    "birthPlace": "Los Angeles, CA, USA",
    "experience": 9,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/3142250/jordin-canada",
    "ppg": 11.6,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/3142250.png"
  },
  {
    "id": "2529137",
    "name": "Natasha Cloud",
    "team": "Chicago Sky",
    "position": "G",
    "jersey": "9",
    "age": 34,
    "height": "5' 10\"",
    "college": "Saint Joseph's",
    "birthPlace": "Broomall, PA, USA",
    "experience": 11,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/2529137/natasha-cloud",
    "ppg": 11.4,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/2529137.png"
  },
  {
    "id": "3142010",
    "name": "Azura Stevens",
    "team": "Chicago Sky",
    "position": "F",
    "jersey": "30",
    "age": 30,
    "height": "6' 6\"",
    "college": "UConn",
    "birthPlace": "Raleigh, NC, USA",
    "experience": 9,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/3142010/azura-stevens",
    "ppg": 10.7,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/3142010.png"
  },
  {
    "id": "869",
    "name": "DeWanna Bonner",
    "team": "Atlanta Dream",
    "position": "F",
    "jersey": "24",
    "age": 39,
    "height": "6' 4\"",
    "college": "Auburn",
    "birthPlace": "Fairfield, AL, USA",
    "experience": 17,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/869/dewanna-bonner",
    "ppg": 10.5,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/869.png"
  },
  {
    "id": "5345325",
    "name": "Awa Fam",
    "team": "Seattle Storm",
    "position": "C",
    "jersey": "11",
    "age": 20,
    "height": "6' 4\"",
    "college": "",
    "birthPlace": "",
    "experience": 0,
    "status": "Out",
    "profile": "https://www.espn.com/wnba/player/_/id/5345325/awa-fam",
    "ppg": 10.3,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/5345325.png"
  },
  {
    "id": "5345444",
    "name": "Laura Juskaite",
    "team": "Toronto Tempo",
    "position": "F",
    "jersey": "2",
    "age": 28,
    "height": "6' 4\"",
    "college": "",
    "birthPlace": "",
    "experience": 0,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/5345444/laura-juskaite",
    "ppg": 10.2,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/5345444.png"
  },
  {
    "id": "4398966",
    "name": "Olivia Nelson-Ododa",
    "team": "Connecticut Sun",
    "position": "C",
    "jersey": "10",
    "age": 26,
    "height": "6' 5\"",
    "college": "UConn",
    "birthPlace": "Winder, GA, USA",
    "experience": 5,
    "status": "Out",
    "profile": "https://www.espn.com/wnba/player/_/id/4398966/olivia-nelson-ododa",
    "ppg": 10.0,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/4398966.png"
  },
  {
    "id": "4398729",
    "name": "Emily Engstler",
    "team": "Portland Fire",
    "position": "F",
    "jersey": "21",
    "age": 26,
    "height": "6' 1\"",
    "college": "Louisville",
    "birthPlace": "New York, NY, USA",
    "experience": 5,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/4398729/emily-engstler",
    "ppg": 10.0,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/4398729.png"
  },
  {
    "id": "4433635",
    "name": "Diamond Miller",
    "team": "Connecticut Sun",
    "position": "F",
    "jersey": "1",
    "age": 25,
    "height": "6' 3\"",
    "college": "Maryland",
    "birthPlace": "Somerset, NJ, USA",
    "experience": 4,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/4433635/diamond-miller",
    "ppg": 9.6,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/4433635.png"
  },
  {
    "id": "4433404",
    "name": "Cameron Brink",
    "team": "Los Angeles Sparks",
    "position": "F",
    "jersey": "22",
    "age": 24,
    "height": "6' 4\"",
    "college": "Stanford",
    "birthPlace": "Beaverton, OR, USA",
    "experience": 3,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/4433404/cameron-brink",
    "ppg": 9.6,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/4433404.png"
  },
  {
    "id": "5017726",
    "name": "Jade Melbourne",
    "team": "Seattle Storm",
    "position": "G",
    "jersey": "5",
    "age": 24,
    "height": "5' 10\"",
    "college": "",
    "birthPlace": "Traralgon, VIC, Australia",
    "experience": 4,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/5017726/jade-melbourne",
    "ppg": 9.5,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/5017726.png"
  },
  {
    "id": "5345320",
    "name": "Pauline Astier",
    "team": "New York Liberty",
    "position": "G",
    "jersey": "18",
    "age": 24,
    "height": "5' 11\"",
    "college": "",
    "birthPlace": "",
    "experience": 0,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/5345320/pauline-astier",
    "ppg": 9.2,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/5345320.png"
  },
  {
    "id": "4398915",
    "name": "Naz Hillmon",
    "team": "Atlanta Dream",
    "position": "F",
    "jersey": "00",
    "age": 26,
    "height": "6' 2\"",
    "college": "Michigan",
    "birthPlace": "Cleveland, OH, USA",
    "experience": 5,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/4398915/naz-hillmon",
    "ppg": 9.1,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/4398915.png"
  },
  {
    "id": "2491214",
    "name": "Erica Wheeler",
    "team": "Los Angeles Sparks",
    "position": "G",
    "jersey": "17",
    "age": 35,
    "height": "5' 7\"",
    "college": "Rutgers",
    "birthPlace": "Miami, FL, USA",
    "experience": 11,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/2491214/erica-wheeler",
    "ppg": 9.0,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/2491214.png"
  },
  {
    "id": "1054",
    "name": "Tiffany Hayes",
    "team": "Golden State Valkyries",
    "position": "G",
    "jersey": "15",
    "age": 36,
    "height": "5' 10\"",
    "college": "UConn",
    "birthPlace": "Lakeland, FL, USA",
    "experience": 14,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/1054/tiffany-hayes",
    "ppg": 8.9,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/1054.png"
  },
  {
    "id": "3910470",
    "name": "Maria Conde",
    "team": "Toronto Tempo",
    "position": "F",
    "jersey": "10",
    "age": 29,
    "height": "6' 3\"",
    "college": "Florida State",
    "birthPlace": "Madrid, Spain",
    "experience": 0,
    "status": "Out",
    "profile": "https://www.espn.com/wnba/player/_/id/3910470/maria-conde",
    "ppg": 8.9,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/3910470.png"
  },
  {
    "id": "4282173",
    "name": "Michaela Onyenwere",
    "team": "Washington Mystics",
    "position": "F",
    "jersey": "12",
    "age": 27,
    "height": "6' 0\"",
    "college": "UCLA",
    "birthPlace": "Aurora, CO, USA",
    "experience": 6,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/4282173/michaela-onyenwere",
    "ppg": 8.9,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/4282173.png"
  },
  {
    "id": "3922628",
    "name": "Kennedy Burke",
    "team": "Connecticut Sun",
    "position": "G",
    "jersey": "25",
    "age": 29,
    "height": "6' 1\"",
    "college": "UCLA",
    "birthPlace": "Northridge, CA, USA",
    "experience": 7,
    "status": "Out",
    "profile": "https://www.espn.com/wnba/player/_/id/3922628/kennedy-burke",
    "ppg": 8.8,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/3922628.png"
  },
  {
    "id": "4257500",
    "name": "Cecilia Zandalasini",
    "team": "Golden State Valkyries",
    "position": "F",
    "jersey": "24",
    "age": 30,
    "height": "6' 2\"",
    "college": "",
    "birthPlace": "Milan, Italy",
    "experience": 5,
    "status": "Out",
    "profile": "https://www.espn.com/wnba/player/_/id/4257500/cecilia-zandalasini",
    "ppg": 8.8,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/4257500.png"
  },
  {
    "id": "3146151",
    "name": "Ariel Atkins",
    "team": "Los Angeles Sparks",
    "position": "G",
    "jersey": "7",
    "age": 30,
    "height": "5' 10\"",
    "college": "Texas",
    "birthPlace": "Dallas, TX, USA",
    "experience": 9,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/3146151/ariel-atkins",
    "ppg": 8.5,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/3146151.png"
  },
  {
    "id": "4038379",
    "name": "Marine Johannes",
    "team": "New York Liberty",
    "position": "G",
    "jersey": "23",
    "age": 31,
    "height": "5' 10\"",
    "college": "",
    "birthPlace": "Lisieux, France",
    "experience": 5,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/4038379/marine-johannes",
    "ppg": 8.5,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/4038379.png"
  },
  {
    "id": "4068042",
    "name": "Natasha Mack",
    "team": "Phoenix Mercury",
    "position": "F",
    "jersey": "4",
    "age": 28,
    "height": "6' 4\"",
    "college": "Oklahoma State",
    "birthPlace": "Lufkin, TX, USA",
    "experience": 4,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/4068042/natasha-mack",
    "ppg": 8.4,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/4068042.png"
  },
  {
    "id": "3907781",
    "name": "Sophie Cunningham",
    "team": "Indiana Fever",
    "position": "G",
    "jersey": "8",
    "age": 30,
    "height": "6' 1\"",
    "college": "Missouri",
    "birthPlace": "Columbia, MO, USA",
    "experience": 8,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/3907781/sophie-cunningham",
    "ppg": 8.3,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/3907781.png"
  },
  {
    "id": "2529622",
    "name": "Kayla Thornton",
    "team": "Golden State Valkyries",
    "position": "F",
    "jersey": "5",
    "age": 33,
    "height": "6' 1\"",
    "college": "UTEP",
    "birthPlace": "El Paso, TX, USA",
    "experience": 11,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/2529622/kayla-thornton",
    "ppg": 7.8,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/2529622.png"
  },
  {
    "id": "2987869",
    "name": "Jewell Loyd",
    "team": "Las Vegas Aces",
    "position": "G",
    "jersey": "24",
    "age": 32,
    "height": "5' 11\"",
    "college": "Notre Dame",
    "birthPlace": "Lincolnwood, IL, USA",
    "experience": 12,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/2987869/jewell-loyd",
    "ppg": 7.7,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/2987869.png"
  },
  {
    "id": "4432832",
    "name": "Zia Cooke",
    "team": "Seattle Storm",
    "position": "G",
    "jersey": "7",
    "age": 25,
    "height": "5' 9\"",
    "college": "South Carolina",
    "birthPlace": "Toledo, OH, USA",
    "experience": 4,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/4432832/zia-cooke",
    "ppg": 7.6,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/4432832.png"
  },
  {
    "id": "4703609",
    "name": "Charlisse Leger-Walker",
    "team": "Connecticut Sun",
    "position": "G",
    "jersey": "4",
    "age": 24,
    "height": "5' 10\"",
    "college": "UCLA",
    "birthPlace": "Waikato, New Zealand",
    "experience": 0,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/4703609/charlisse-leger-walker",
    "ppg": 7.2,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/4703609.png"
  },
  {
    "id": "4433514",
    "name": "Saniya Rivers",
    "team": "Connecticut Sun",
    "position": "G",
    "jersey": "22",
    "age": 23,
    "height": "6' 1\"",
    "college": "NC State",
    "birthPlace": "Wilmington, NC, USA",
    "experience": 2,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/4433514/saniya-rivers",
    "ppg": 7.1,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/4433514.png"
  },
  {
    "id": "4899328",
    "name": "Kaitlyn Chen",
    "team": "Golden State Valkyries",
    "position": "G",
    "jersey": "2",
    "age": 24,
    "height": "5' 9\"",
    "college": "UConn",
    "birthPlace": "San Marino, CA, USA",
    "experience": 2,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/4899328/kaitlyn-chen",
    "ppg": 6.8,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/4899328.png"
  },
  {
    "id": "3142255",
    "name": "Monique Billings",
    "team": "Indiana Fever",
    "position": "F",
    "jersey": "25",
    "age": 30,
    "height": "6' 4\"",
    "college": "UCLA",
    "birthPlace": "Corona, CA, USA",
    "experience": 9,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/3142255/monique-billings",
    "ppg": 6.8,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/3142255.png"
  },
  {
    "id": "4704180",
    "name": "Georgia Amoore",
    "team": "Washington Mystics",
    "position": "G",
    "jersey": "8",
    "age": 25,
    "height": "5' 6\"",
    "college": "Kentucky",
    "birthPlace": "Ballarat, VIC, Australia",
    "experience": 0,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/4704180/georgia-amoore",
    "ppg": 6.6,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/4704180.png"
  },
  {
    "id": "4858656",
    "name": "Gabriela Jaquez",
    "team": "Chicago Sky",
    "position": "G",
    "jersey": "11",
    "age": 22,
    "height": "6' 0\"",
    "college": "UCLA",
    "birthPlace": "Camarillo, CA, USA",
    "experience": 0,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/4858656/gabriela-jaquez",
    "ppg": 6.5,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/4858656.png"
  },
  {
    "id": "4432865",
    "name": "Jacy Sheldon",
    "team": "Chicago Sky",
    "position": "G",
    "jersey": "0",
    "age": 26,
    "height": "5' 10\"",
    "college": "Ohio State",
    "birthPlace": "Dublin, OH, USA",
    "experience": 3,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/4432865/jacy-sheldon",
    "ppg": 6.4,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/4432865.png"
  },
  {
    "id": "3054590",
    "name": "Nia Coffey",
    "team": "Minnesota Lynx",
    "position": "F",
    "jersey": "12",
    "age": 31,
    "height": "6' 1\"",
    "college": "Northwestern",
    "birthPlace": "Saint Paul, MN, USA",
    "experience": 10,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/3054590/nia-coffey",
    "ppg": 6.4,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/3054590.png"
  },
  {
    "id": "4337216",
    "name": "Han Xu",
    "team": "New York Liberty",
    "position": "C",
    "jersey": "21",
    "age": 26,
    "height": "6' 11\"",
    "college": "",
    "birthPlace": "Hebei, China",
    "experience": 4,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/4337216/han-xu",
    "ppg": 6.4,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/4337216.png"
  },
  {
    "id": "4399415",
    "name": "Maddy Siegrist",
    "team": "Dallas Wings",
    "position": "F",
    "jersey": "20",
    "age": 26,
    "height": "6' 2\"",
    "college": "Villanova",
    "birthPlace": "Poughkeepsie, NY, USA",
    "experience": 4,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/4399415/maddy-siegrist",
    "ppg": 6.3,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/4399415.png"
  },
  {
    "id": "3919496",
    "name": "Valeriane Ayayi",
    "team": "Phoenix Mercury",
    "position": "F",
    "jersey": "11",
    "age": 32,
    "height": "6' 1\"",
    "college": "",
    "birthPlace": "Bordeaux, France",
    "experience": 2,
    "status": "Out",
    "profile": "https://www.espn.com/wnba/player/_/id/3919496/valeriane-ayayi",
    "ppg": 6.3,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/3919496.png"
  },
  {
    "id": "5105406",
    "name": "Frieda Buhner",
    "team": "Portland Fire",
    "position": "F",
    "jersey": "20",
    "age": 22,
    "height": "6' 1\"",
    "college": "Florida",
    "birthPlace": "Osnabruck, Germany",
    "experience": 0,
    "status": "Out",
    "profile": "https://www.espn.com/wnba/player/_/id/5105406/frieda-buhner",
    "ppg": 6.3,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/5105406.png"
  },
  {
    "id": "4001679",
    "name": "Julie Allemand",
    "team": "Toronto Tempo",
    "position": "G",
    "jersey": "22",
    "age": 30,
    "height": "5' 10\"",
    "college": "",
    "birthPlace": "Brussels, Belgium",
    "experience": 4,
    "status": "Out",
    "profile": "https://www.espn.com/wnba/player/_/id/4001679/julie-allemand",
    "ppg": 6.3,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/4001679.png"
  },
  {
    "id": "5105737",
    "name": "Lauren Betts",
    "team": "Washington Mystics",
    "position": "C",
    "jersey": "51",
    "age": 22,
    "height": "6' 7\"",
    "college": "UCLA",
    "birthPlace": "Centennial, CO, USA",
    "experience": 0,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/5105737/lauren-betts",
    "ppg": 6.3,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/5105737.png"
  },
  {
    "id": "4583144",
    "name": "Cotie McMahon",
    "team": "Washington Mystics",
    "position": "G",
    "jersey": "23",
    "age": 22,
    "height": "6' 0\"",
    "college": "Ole Miss",
    "birthPlace": "Dayton, OH, USA",
    "experience": 0,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/4583144/cotie-mcmahon",
    "ppg": 6.3,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/4583144.png"
  },
  {
    "id": "4065780",
    "name": "Kaila Charles",
    "team": "Golden State Valkyries",
    "position": "G",
    "jersey": "6",
    "age": 28,
    "height": "6' 1\"",
    "college": "Maryland",
    "birthPlace": "Glenn Dale, MD, USA",
    "experience": 6,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/4065780/kaila-charles",
    "ppg": 6.2,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/4065780.png"
  },
  {
    "id": "5345524",
    "name": "Noemie Brochant",
    "team": "Phoenix Mercury",
    "position": "F",
    "jersey": "1",
    "age": 26,
    "height": "5' 11\"",
    "college": "",
    "birthPlace": "",
    "experience": 0,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/5345524/noemie-brochant",
    "ppg": 6.2,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/5345524.png"
  },
  {
    "id": "4433807",
    "name": "Aziaha James",
    "team": "Dallas Wings",
    "position": "G",
    "jersey": "10",
    "age": 23,
    "height": "5' 10\"",
    "college": "NC State",
    "birthPlace": "Virginia Beach, VA, USA",
    "experience": 2,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/4433807/aziaha-james",
    "ppg": 6.1,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/4433807.png"
  },
  {
    "id": "3913881",
    "name": "Alanna Smith",
    "team": "Dallas Wings",
    "position": "F",
    "jersey": "8",
    "age": 29,
    "height": "6' 4\"",
    "college": "Stanford",
    "birthPlace": "Hobart, TAS, Australia",
    "experience": 8,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/3913881/alanna-smith",
    "ppg": 6.0,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/3913881.png"
  },
  {
    "id": "4790266",
    "name": "Awak Kuier",
    "team": "Dallas Wings",
    "position": "F",
    "jersey": "34",
    "age": 25,
    "height": "6' 6\"",
    "college": "",
    "birthPlace": "",
    "experience": 4,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/4790266/awak-kuier",
    "ppg": 5.9,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/4790266.png"
  },
  {
    "id": "5346554",
    "name": "Teja Oblak",
    "team": "Portland Fire",
    "position": "G",
    "jersey": "7",
    "age": 35,
    "height": "5' 8\"",
    "college": "",
    "birthPlace": "",
    "experience": 0,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/5346554/teja-oblak",
    "ppg": 5.6,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/5346554.png"
  },
  {
    "id": "4433546",
    "name": "Makayla Timpson",
    "team": "Indiana Fever",
    "position": "F",
    "jersey": "21",
    "age": 23,
    "height": "6' 2\"",
    "college": "Florida State",
    "birthPlace": "Edison, GA, USA",
    "experience": 2,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/4433546/makayla-timpson",
    "ppg": 5.5,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/4433546.png"
  },
  {
    "id": "5108587",
    "name": "Madina Okot",
    "team": "Atlanta Dream",
    "position": "C",
    "jersey": "11",
    "age": 22,
    "height": "6' 6\"",
    "college": "South Carolina",
    "birthPlace": "Mumias, Kenya",
    "experience": 0,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/5108587/madina-okot",
    "ppg": 5.4,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/5108587.png"
  },
  {
    "id": "4398829",
    "name": "Lexie Hull",
    "team": "Indiana Fever",
    "position": "G",
    "jersey": "10",
    "age": 26,
    "height": "6' 2\"",
    "college": "Stanford",
    "birthPlace": "Spokane, WA, USA",
    "experience": 5,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/4398829/lexie-hull",
    "ppg": 5.4,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/4398829.png"
  },
  {
    "id": "3142327",
    "name": "Kia Nurse",
    "team": "Toronto Tempo",
    "position": "G",
    "jersey": "11",
    "age": 30,
    "height": "6' 1\"",
    "college": "UConn",
    "birthPlace": "Hamilton, ON, Canada",
    "experience": 8,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/3142327/kia-nurse",
    "ppg": 5.4,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/3142327.png"
  },
  {
    "id": "2327695",
    "name": "Rebekah Gardner",
    "team": "New York Liberty",
    "position": "G",
    "jersey": "7",
    "age": 36,
    "height": "6' 1\"",
    "college": "UCLA",
    "birthPlace": "Upland, CA, USA",
    "experience": 4,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/2327695/rebekah-gardner",
    "ppg": 5.3,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/2327695.png"
  },
  {
    "id": "2566081",
    "name": "Elizabeth Williams",
    "team": "Chicago Sky",
    "position": "C",
    "jersey": "1",
    "age": 33,
    "height": "6' 3\"",
    "college": "Duke",
    "birthPlace": "Virginia Beach, VA, USA",
    "experience": 12,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/2566081/elizabeth-williams",
    "ppg": 5.0,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/2566081.png"
  },
  {
    "id": "4399342",
    "name": "Lexi Held",
    "team": "Phoenix Mercury",
    "position": "G",
    "jersey": "10",
    "age": 26,
    "height": "5' 10\"",
    "college": "DePaul",
    "birthPlace": "Burlington, KY, USA",
    "experience": 2,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/4399342/lexi-held",
    "ppg": 4.9,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/4399342.png"
  },
  {
    "id": "4433433",
    "name": "Aicha Coulibaly",
    "team": "Chicago Sky",
    "position": "G",
    "jersey": "35",
    "age": 24,
    "height": "6' 0\"",
    "college": "Texas A&M",
    "birthPlace": "Bamako, Mali",
    "experience": 0,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/4433433/aicha-coulibaly",
    "ppg": 4.8,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/4433433.png"
  },
  {
    "id": "2529047",
    "name": "Odyssey Sims",
    "team": "Dallas Wings",
    "position": "G",
    "jersey": "1",
    "age": 34,
    "height": "5' 8\"",
    "college": "Baylor",
    "birthPlace": "Irving, TX, USA",
    "experience": 13,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/2529047/odyssey-sims",
    "ppg": 4.8,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/2529047.png"
  },
  {
    "id": "2566186",
    "name": "Rachel Banham",
    "team": "Chicago Sky",
    "position": "G",
    "jersey": "24",
    "age": 33,
    "height": "5' 10\"",
    "college": "Minnesota",
    "birthPlace": "Lakeville, MN, USA",
    "experience": 11,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/2566186/rachel-banham",
    "ppg": 4.7,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/2566186.png"
  },
  {
    "id": "4432830",
    "name": "Jordan Horston",
    "team": "Seattle Storm",
    "position": "F",
    "jersey": "23",
    "age": 25,
    "height": "6' 2\"",
    "college": "Tennessee",
    "birthPlace": "Columbus, OH, USA",
    "experience": 3,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/4432830/jordan-horston",
    "ppg": 4.7,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/4432830.png"
  },
  {
    "id": "5208983",
    "name": "Isobel Borlase",
    "team": "Atlanta Dream",
    "position": "G",
    "jersey": "20",
    "age": 21,
    "height": "5' 11\"",
    "college": "",
    "birthPlace": "Melbourne, VIC, Australia",
    "experience": 0,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/5208983/isobel-borlase",
    "ppg": 4.6,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/5208983.png"
  },
  {
    "id": "3056730",
    "name": "Karlie Samuelson",
    "team": "Portland Fire",
    "position": "G",
    "jersey": "44",
    "age": 31,
    "height": "6' 0\"",
    "college": "Stanford",
    "birthPlace": "Huntington Beach, CA, USA",
    "experience": 8,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/3056730/karlie-samuelson",
    "ppg": 4.5,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/3056730.png"
  },
  {
    "id": "3917453",
    "name": "Katie Lou Samuelson",
    "team": "Seattle Storm",
    "position": "F",
    "jersey": "33",
    "age": 29,
    "height": "6' 3\"",
    "college": "UConn",
    "birthPlace": "Huntington Beach, CA, USA",
    "experience": 6,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/3917453/katie-lou-samuelson",
    "ppg": 4.4,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/3917453.png"
  },
  {
    "id": "5108550",
    "name": "Serah Williams",
    "team": "Portland Fire",
    "position": "C",
    "jersey": "25",
    "age": 22,
    "height": "6' 4\"",
    "college": "UConn",
    "birthPlace": "Brooklyn, NY, USA",
    "experience": 0,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/5108550/serah-williams",
    "ppg": 4.3,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/5108550.png"
  },
  {
    "id": "5345319",
    "name": "Nell Angloma",
    "team": "Connecticut Sun",
    "position": "F",
    "jersey": "33",
    "age": 20,
    "height": "6' 1\"",
    "college": "",
    "birthPlace": "",
    "experience": 0,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/5345319/nell-angloma",
    "ppg": 4.2,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/5345319.png"
  },
  {
    "id": "4065760",
    "name": "Tyasha Harris",
    "team": "Indiana Fever",
    "position": "G",
    "jersey": "52",
    "age": 28,
    "height": "5' 10\"",
    "college": "South Carolina",
    "birthPlace": "Noblesville, IN, USA",
    "experience": 7,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/4065760/tyasha-harris",
    "ppg": 4.2,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/4065760.png"
  },
  {
    "id": "4280850",
    "name": "Maya Caldwell",
    "team": "Minnesota Lynx",
    "position": "G",
    "jersey": "3",
    "age": 27,
    "height": "5' 11\"",
    "college": "Georgia",
    "birthPlace": "Charlotte, NC, USA",
    "experience": 5,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/4280850/maya-caldwell",
    "ppg": 4.0,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/4280850.png"
  },
  {
    "id": "5209202",
    "name": "Nyadiew Puoch",
    "team": "Portland Fire",
    "position": "F",
    "jersey": "13",
    "age": 22,
    "height": "6' 3\"",
    "college": "",
    "birthPlace": "",
    "experience": 0,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/5209202/nyadiew-puoch",
    "ppg": 3.9,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/5209202.png"
  },
  {
    "id": "5105732",
    "name": "Raegan Beers",
    "team": "Connecticut Sun",
    "position": "F",
    "jersey": "15",
    "age": 23,
    "height": "6' 4\"",
    "college": "Oklahoma",
    "birthPlace": "Littleton, CO, USA",
    "experience": 0,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/5105732/raegan-beers",
    "ppg": 3.7,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/5105732.png"
  },
  {
    "id": "4433431",
    "name": "Te-Hina Paopao",
    "team": "Atlanta Dream",
    "position": "G",
    "jersey": "2",
    "age": 24,
    "height": "5' 9\"",
    "college": "South Carolina",
    "birthPlace": "Oceanside, CA, USA",
    "experience": 2,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/4433431/te-hina-paopao",
    "ppg": 3.6,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/4433431.png"
  },
  {
    "id": "2590093",
    "name": "Kiah Stokes",
    "team": "Golden State Valkyries",
    "position": "C",
    "jersey": "41",
    "age": 33,
    "height": "6' 3\"",
    "college": "UConn",
    "birthPlace": "Cedar Rapids, IA, USA",
    "experience": 11,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/2590093/kiah-stokes",
    "ppg": 3.6,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/2590093.png"
  },
  {
    "id": "3142055",
    "name": "Myisha Hines-Allen",
    "team": "Indiana Fever",
    "position": "F",
    "jersey": "2",
    "age": 31,
    "height": "6' 2\"",
    "college": "Louisville",
    "birthPlace": "Montclair, NJ, USA",
    "experience": 9,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/3142055/myisha-hines-allen",
    "ppg": 3.6,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/3142055.png"
  },
  {
    "id": "5278237",
    "name": "Anastasiia Olairi Kosu",
    "team": "Minnesota Lynx",
    "position": "F",
    "jersey": "7",
    "age": 21,
    "height": "6' 1\"",
    "college": "",
    "birthPlace": "",
    "experience": 2,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/5278237/anastasiia-olairi-kosu",
    "ppg": 3.6,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/5278237.png"
  },
  {
    "id": "3099736",
    "name": "Stephanie Talbot",
    "team": "Las Vegas Aces",
    "position": "F",
    "jersey": "7",
    "age": 32,
    "height": "6' 2\"",
    "college": "",
    "birthPlace": "Darwin, NT, Australia",
    "experience": 8,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/3099736/stephanie-talbot",
    "ppg": 3.5,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/3099736.png"
  },
  {
    "id": "4432834",
    "name": "Laeticia Amihere",
    "team": "Golden State Valkyries",
    "position": "F",
    "jersey": "3",
    "age": 25,
    "height": "6' 3\"",
    "college": "South Carolina",
    "birthPlace": "Mississauga, AB, Canada",
    "experience": 4,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/4432834/laeticia-amihere",
    "ppg": 3.4,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/4432834.png"
  },
  {
    "id": "4336633",
    "name": "Li Yueru",
    "team": "Dallas Wings",
    "position": "C",
    "jersey": "28",
    "age": 27,
    "height": "6' 7\"",
    "college": "",
    "birthPlace": "Tai Yuan, China",
    "experience": 4,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/4336633/li-yueru",
    "ppg": 3.3,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/4336633.png"
  },
  {
    "id": "5208985",
    "name": "Alicia Florez",
    "team": "Washington Mystics",
    "position": "G",
    "jersey": "2",
    "age": 22,
    "height": "5' 9\"",
    "college": "",
    "birthPlace": "",
    "experience": 0,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/5208985/alicia-florez",
    "ppg": 3.3,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/5208985.png"
  },
  {
    "id": "2529183",
    "name": "Stefanie Dolson",
    "team": "Seattle Storm",
    "position": "C",
    "jersey": "31",
    "age": 34,
    "height": "6' 5\"",
    "college": "UConn",
    "birthPlace": "Port Jervis, NY, USA",
    "experience": 13,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/2529183/stefanie-dolson",
    "ppg": 3.2,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/2529183.png"
  },
  {
    "id": "4433797",
    "name": "Raven Johnson",
    "team": "Indiana Fever",
    "position": "G",
    "jersey": "3",
    "age": 23,
    "height": "5' 8\"",
    "college": "South Carolina",
    "birthPlace": "Atlanta, GA, USA",
    "experience": 0,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/4433797/raven-johnson",
    "ppg": 3.1,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/4433797.png"
  },
  {
    "id": "4898898",
    "name": "Gianna Kneepkens",
    "team": "Connecticut Sun",
    "position": "G",
    "jersey": "5",
    "age": 23,
    "height": "5' 11\"",
    "college": "UCLA",
    "birthPlace": "Duluth, MN, USA",
    "experience": 0,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/4898898/gianna-kneepkens",
    "ppg": 3.0,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/4898898.png"
  },
  {
    "id": "5105729",
    "name": "Chance Gray",
    "team": "Los Angeles Sparks",
    "position": "G",
    "jersey": "2",
    "age": 22,
    "height": "5' 9\"",
    "college": "Ohio State",
    "birthPlace": "Cincinnati, OH, USA",
    "experience": 0,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/5105729/chance-gray",
    "ppg": 2.9,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/5105729.png"
  },
  {
    "id": "4873358",
    "name": "Antonia Delaere",
    "team": "Minnesota Lynx",
    "position": "F",
    "jersey": "8",
    "age": 32,
    "height": "5' 11\"",
    "college": "",
    "birthPlace": "Antwerp, Belgium",
    "experience": 0,
    "status": "Out",
    "profile": "https://www.espn.com/wnba/player/_/id/4873358/antonia-delaere",
    "ppg": 2.9,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/4873358.png"
  },
  {
    "id": "4433411",
    "name": "Angela Dugalic",
    "team": "Washington Mystics",
    "position": "F",
    "jersey": "32",
    "age": 24,
    "height": "6' 4\"",
    "college": "UCLA",
    "birthPlace": "Des Plaines, IL, USA",
    "experience": 0,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/4433411/angela-dugalic",
    "ppg": 2.9,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/4433411.png"
  },
  {
    "id": "4874375",
    "name": "Jihyun Park",
    "team": "Los Angeles Sparks",
    "position": "F",
    "jersey": "6",
    "age": 26,
    "height": "6' 1\"",
    "college": "",
    "birthPlace": "",
    "experience": 0,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/4874375/jihyun-park",
    "ppg": 2.2,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/4874375.png"
  },
  {
    "id": "5122345",
    "name": "Cassandre Prosper",
    "team": "Washington Mystics",
    "position": "G",
    "jersey": "18",
    "age": 21,
    "height": "6' 3\"",
    "college": "Notre Dame",
    "birthPlace": "Montreal, PQ, Canada",
    "experience": 0,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/5122345/cassandre-prosper",
    "ppg": 2.1,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/5122345.png"
  },
  {
    "id": "4434020",
    "name": "Teonni Key",
    "team": "Toronto Tempo",
    "position": "F",
    "jersey": "7",
    "age": 23,
    "height": "6' 5\"",
    "college": "Kentucky",
    "birthPlace": "Cary, NC, USA",
    "experience": 0,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/4434020/teonni-key",
    "ppg": 2.0,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/4434020.png"
  },
  {
    "id": "5017721",
    "name": "Sika Kone",
    "team": "Atlanta Dream",
    "position": "F",
    "jersey": "23",
    "age": 24,
    "height": "6' 3\"",
    "college": "",
    "birthPlace": "",
    "experience": 4,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/5017721/sika-kone",
    "ppg": 1.7,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/5017721.png"
  },
  {
    "id": "3142086",
    "name": "Brianna Turner",
    "team": "Las Vegas Aces",
    "position": "F",
    "jersey": "21",
    "age": 30,
    "height": "6' 3\"",
    "college": "Notre Dame",
    "birthPlace": "Pearland, TX, USA",
    "experience": 8,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/3142086/brianna-turner",
    "ppg": 1.7,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/3142086.png"
  },
  {
    "id": "3058895",
    "name": "Brionna Jones",
    "team": "Atlanta Dream",
    "position": "Player",
    "jersey": "42",
    "age": 30,
    "height": "6' 3\"",
    "college": "Maryland",
    "birthPlace": "Havre De Grace, MD, USA",
    "experience": 10,
    "status": "Out",
    "profile": "https://www.espn.com/wnba/player/_/id/3058895/brionna-jones",
    "ppg": 0.0,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/3058895.png"
  },
  {
    "id": "5105740",
    "name": "Indya Nivar",
    "team": "Atlanta Dream",
    "position": "Player",
    "jersey": "21",
    "age": 22,
    "height": "5' 10\"",
    "college": "North Carolina",
    "birthPlace": "Apex, NC, USA",
    "experience": 0,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/5105740/indya-nivar",
    "ppg": 0.0,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/5105740.png"
  },
  {
    "id": "3058893",
    "name": "Shatori Walker-Kimbrough",
    "team": "Atlanta Dream",
    "position": "Player",
    "jersey": "33",
    "age": 31,
    "height": "5' 9\"",
    "college": "Maryland",
    "birthPlace": "Baltimore, MD, USA",
    "experience": 10,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/3058893/shatori-walker-kimbrough",
    "ppg": 0.0,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/3058893.png"
  },
  {
    "id": "4066548",
    "name": "DiJonai Carrington",
    "team": "Chicago Sky",
    "position": "Player",
    "jersey": "7",
    "age": 28,
    "height": "5' 11\"",
    "college": "Baylor",
    "birthPlace": "San Diego, CA, USA",
    "experience": 6,
    "status": "Out",
    "profile": "https://www.espn.com/wnba/player/_/id/4066548/dijonai-carrington",
    "ppg": 0.0,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/4066548.png"
  },
  {
    "id": "2491205",
    "name": "Skylar Diggins",
    "team": "Chicago Sky",
    "position": "Player",
    "jersey": "4",
    "age": 36,
    "height": "5' 9\"",
    "college": "Notre Dame",
    "birthPlace": "South Bend, IN, USA",
    "experience": 12,
    "status": "Out",
    "profile": "https://www.espn.com/wnba/player/_/id/2491205/skylar-diggins",
    "ppg": 0.0,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/2491205.png"
  },
  {
    "id": "4433630",
    "name": "Rickea Jackson",
    "team": "Chicago Sky",
    "position": "Player",
    "jersey": "5",
    "age": 25,
    "height": "6' 2\"",
    "college": "Tennessee",
    "birthPlace": "Detroit, MI, USA",
    "experience": 3,
    "status": "Out",
    "profile": "https://www.espn.com/wnba/player/_/id/4433630/rickea-jackson",
    "ppg": 0.0,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/4433630.png"
  },
  {
    "id": "4599199",
    "name": "Morgan Maly",
    "team": "Chicago Sky",
    "position": "Player",
    "jersey": "15",
    "age": 24,
    "height": "6' 1\"",
    "college": "Creighton",
    "birthPlace": "Crete, NE, USA",
    "experience": 0,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/4599199/morgan-maly",
    "ppg": 0.0,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/4599199.png"
  },
  {
    "id": "981",
    "name": "Courtney Vandersloot",
    "team": "Chicago Sky",
    "position": "Player",
    "jersey": "22",
    "age": 37,
    "height": "5' 8\"",
    "college": "Gonzaga",
    "birthPlace": "Kent, WA, USA",
    "experience": 16,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/981/courtney-vandersloot",
    "ppg": 0.0,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/981.png"
  },
  {
    "id": "4433408",
    "name": "Aaliyah Edwards",
    "team": "Connecticut Sun",
    "position": "Player",
    "jersey": "8",
    "age": 24,
    "height": "6' 3\"",
    "college": "UConn",
    "birthPlace": "Kingston, ON, Canada",
    "experience": 3,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/4433408/aaliyah-edwards",
    "ppg": 0.0,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/4433408.png"
  },
  {
    "id": "2490553",
    "name": "Brittney Griner",
    "team": "Connecticut Sun",
    "position": "Player",
    "jersey": "42",
    "age": 35,
    "height": "6' 9\"",
    "college": "Baylor",
    "birthPlace": "Houston, TX, USA",
    "experience": 13,
    "status": "Out",
    "profile": "https://www.espn.com/wnba/player/_/id/2490553/brittney-griner",
    "ppg": 0.0,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/2490553.png"
  },
  {
    "id": "5106232",
    "name": "Ashlon Jackson",
    "team": "Connecticut Sun",
    "position": "Player",
    "jersey": "3",
    "age": 22,
    "height": "6' 0\"",
    "college": "Duke",
    "birthPlace": "China, TX, USA",
    "experience": 0,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/5106232/ashlon-jackson",
    "ppg": 0.0,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/5106232.png"
  },
  {
    "id": "5208981",
    "name": "Leila Lacan",
    "team": "Connecticut Sun",
    "position": "Player",
    "jersey": "47",
    "age": 22,
    "height": "5' 11\"",
    "college": "",
    "birthPlace": "Rodez, France",
    "experience": 2,
    "status": "Out",
    "profile": "https://www.espn.com/wnba/player/_/id/5208981/leila-lacan",
    "ppg": 0.0,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/5208981.png"
  },
  {
    "id": "4433792",
    "name": "Rayah Marshall",
    "team": "Connecticut Sun",
    "position": "Player",
    "jersey": "13",
    "age": 22,
    "height": "6' 4\"",
    "college": "USC",
    "birthPlace": "Los Angeles, CA, USA",
    "experience": 1,
    "status": "Out",
    "profile": "https://www.espn.com/wnba/player/_/id/4433792/rayah-marshall",
    "ppg": 0.0,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/4433792.png"
  },
  {
    "id": "4433412",
    "name": "Hailey Van Lith",
    "team": "Connecticut Sun",
    "position": "Player",
    "jersey": "2",
    "age": 24,
    "height": "5' 9\"",
    "college": "TCU",
    "birthPlace": "Wenatchee, WA, USA",
    "experience": 2,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/4433412/hailey-van-lith",
    "ppg": 0.0,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/4433412.png"
  },
  {
    "id": "924",
    "name": "Alysha Clark",
    "team": "Dallas Wings",
    "position": "Player",
    "jersey": "7",
    "age": 39,
    "height": "5' 11\"",
    "college": "Middle Tennessee",
    "birthPlace": "Denver, CO, USA",
    "experience": 14,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/924/alysha-clark",
    "ppg": 0.0,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/924.png"
  },
  {
    "id": "4595910",
    "name": "Haley Jones",
    "team": "Dallas Wings",
    "position": "Player",
    "jersey": "30",
    "age": 25,
    "height": "6' 1\"",
    "college": "Stanford",
    "birthPlace": "Santa Cruz, CA, USA",
    "experience": 4,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/4595910/haley-jones",
    "ppg": 0.0,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/4595910.png"
  },
  {
    "id": "4068159",
    "name": "Sug Sutton",
    "team": "Dallas Wings",
    "position": "Player",
    "jersey": "0",
    "age": 27,
    "height": "5' 8\"",
    "college": "Texas",
    "birthPlace": "Saint Louis, MO, USA",
    "experience": 5,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/4068159/sug-sutton",
    "ppg": 0.0,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/4068159.png"
  },
  {
    "id": "5345473",
    "name": "Costanza Verona",
    "team": "Dallas Wings",
    "position": "Player",
    "jersey": "6",
    "age": 27,
    "height": "5' 6\"",
    "college": "",
    "birthPlace": "Palermo, Italy",
    "experience": 0,
    "status": "Out",
    "profile": "https://www.espn.com/wnba/player/_/id/5345473/costanza-verona",
    "ppg": 0.0,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/5345473.png"
  },
  {
    "id": "4398965",
    "name": "Christyn Williams",
    "team": "Dallas Wings",
    "position": "Player",
    "jersey": "31",
    "age": 26,
    "height": "5' 11\"",
    "college": "UConn",
    "birthPlace": "Little Rock, AR, USA",
    "experience": 1,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/4398965/christyn-williams",
    "ppg": 0.0,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/4398965.png"
  },
  {
    "id": "4066546",
    "name": "Nadia Fingall",
    "team": "Golden State Valkyries",
    "position": "Player",
    "jersey": "45",
    "age": 28,
    "height": "6' 4\"",
    "college": "Stanford",
    "birthPlace": "Navarre, FL, USA",
    "experience": 0,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/4066546/nadia-fingall",
    "ppg": 0.0,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/4066546.png"
  },
  {
    "id": "5277552",
    "name": "Juste Jocyte",
    "team": "Golden State Valkyries",
    "position": "Player",
    "jersey": "4",
    "age": 20,
    "height": "6' 0\"",
    "college": "",
    "birthPlace": "",
    "experience": 0,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/5277552/juste-jocyte",
    "ppg": 0.0,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/5277552.png"
  },
  {
    "id": "4433634",
    "name": "Ashten Prechtel",
    "team": "Golden State Valkyries",
    "position": "Player",
    "jersey": "11",
    "age": 25,
    "height": "6' 5\"",
    "college": "Stanford",
    "birthPlace": "Colorado Springs, CO, USA",
    "experience": 0,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/4433634/ashten-prechtel",
    "ppg": 0.0,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/4433634.png"
  },
  {
    "id": "4790263",
    "name": "Iliana Rupert",
    "team": "Golden State Valkyries",
    "position": "Player",
    "jersey": "12",
    "age": 25,
    "height": "6' 4\"",
    "college": "",
    "birthPlace": "",
    "experience": 4,
    "status": "Out",
    "profile": "https://www.espn.com/wnba/player/_/id/4790263/iliana-rupert",
    "ppg": 0.0,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/4790263.png"
  },
  {
    "id": "4398577",
    "name": "Miela Sowah",
    "team": "Golden State Valkyries",
    "position": "Player",
    "jersey": "7",
    "age": 26,
    "height": "5' 10\"",
    "college": "Duke",
    "birthPlace": "Rockhampton, QLD, Australia",
    "experience": 0,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/4398577/miela-sowah",
    "ppg": 0.0,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/4398577.png"
  },
  {
    "id": "4898383",
    "name": "Bree Hall",
    "team": "Indiana Fever",
    "position": "Player",
    "jersey": "23",
    "age": 23,
    "height": "6' 1\"",
    "college": "South Carolina",
    "birthPlace": "Dayton, OH, USA",
    "experience": 2,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/4898383/bree-hall",
    "ppg": 0.0,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/4898383.png"
  },
  {
    "id": "4433744",
    "name": "Michelle Onyiah",
    "team": "Indiana Fever",
    "position": "Player",
    "jersey": "1",
    "age": 23,
    "height": "6' 3\"",
    "college": "California",
    "birthPlace": "Eastvale, CA, USA",
    "experience": 0,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/4433744/michelle-onyiah",
    "ppg": 0.0,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/4433744.png"
  },
  {
    "id": "3056672",
    "name": "Mercedes Russell",
    "team": "Indiana Fever",
    "position": "Player",
    "jersey": "5",
    "age": 31,
    "height": "6' 6\"",
    "college": "Tennessee",
    "birthPlace": "Springfield, OR, USA",
    "experience": 7,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/3056672/mercedes-russell",
    "ppg": 0.0,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/3056672.png"
  },
  {
    "id": "5105731",
    "name": "Grace VanSlooten",
    "team": "Indiana Fever",
    "position": "Player",
    "jersey": "14",
    "age": 22,
    "height": "6' 3\"",
    "college": "Michigan State",
    "birthPlace": "Toledo, OH, USA",
    "experience": 0,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/5105731/grace-vanslooten",
    "ppg": 0.0,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/5105731.png"
  },
  {
    "id": "4433633",
    "name": "Kierstan Bell",
    "team": "Las Vegas Aces",
    "position": "Player",
    "jersey": "1",
    "age": 26,
    "height": "6' 1\"",
    "college": "Florida Gulf Coast",
    "birthPlace": "Alliance, OH, USA",
    "experience": 5,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/4433633/kierstan-bell",
    "ppg": 0.0,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/4433633.png"
  },
  {
    "id": "3916514",
    "name": "Kalani Brown",
    "team": "Las Vegas Aces",
    "position": "Player",
    "jersey": "21",
    "age": 29,
    "height": "6' 7\"",
    "college": "Baylor",
    "birthPlace": "Slidell, LA, USA",
    "experience": 5,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/3916514/kalani-brown",
    "ppg": 0.0,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/3916514.png"
  },
  {
    "id": "4281190",
    "name": "Dana Evans",
    "team": "Las Vegas Aces",
    "position": "Player",
    "jersey": "11",
    "age": 28,
    "height": "5' 6\"",
    "college": "Louisville",
    "birthPlace": "Gary, IN, USA",
    "experience": 6,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/4281190/dana-evans",
    "ppg": 0.0,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/4281190.png"
  },
  {
    "id": "4609797",
    "name": "Ta'Niya Latson",
    "team": "Las Vegas Aces",
    "position": "Player",
    "jersey": "5",
    "age": 22,
    "height": "5' 8\"",
    "college": "South Carolina",
    "birthPlace": "Miami, FL, USA",
    "experience": 0,
    "status": "Out",
    "profile": "https://www.espn.com/wnba/player/_/id/4609797/taniya-latson",
    "ppg": 0.0,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/4609797.png"
  },
  {
    "id": "2529458",
    "name": "Cheyenne Parker-Tyus",
    "team": "Las Vegas Aces",
    "position": "Player",
    "jersey": "32",
    "age": 34,
    "height": "6' 4\"",
    "college": "Middle Tennessee",
    "birthPlace": "Queens, NY, USA",
    "experience": 12,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/2529458/cheyenne-parker-tyus",
    "ppg": 0.0,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/2529458.png"
  },
  {
    "id": "4682855",
    "name": "Justine Pissott",
    "team": "Las Vegas Aces",
    "position": "Player",
    "jersey": "13",
    "age": 22,
    "height": "6' 4\"",
    "college": "Vanderbilt",
    "birthPlace": "Toms River, NJ, USA",
    "experience": 0,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/4682855/justine-pissott",
    "ppg": 0.0,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/4682855.png"
  },
  {
    "id": "5220104",
    "name": "Mai Yamamoto",
    "team": "Las Vegas Aces",
    "position": "Player",
    "jersey": "18",
    "age": 26,
    "height": "5' 5\"",
    "college": "",
    "birthPlace": "Hiroshima, Japan",
    "experience": 0,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/5220104/mai-yamamoto",
    "ppg": 0.0,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/5220104.png"
  },
  {
    "id": "5274110",
    "name": "Monique Akoa Makani",
    "team": "Los Angeles Sparks",
    "position": "Player",
    "jersey": "1",
    "age": 25,
    "height": "5' 11\"",
    "college": "",
    "birthPlace": "Bafang, Cameroon",
    "experience": 2,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/5274110/monique-akoa-makani",
    "ppg": 0.0,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/5274110.png"
  },
  {
    "id": "2284331",
    "name": "Emma Cannon",
    "team": "Los Angeles Sparks",
    "position": "Player",
    "jersey": "32",
    "age": 37,
    "height": "6' 2\"",
    "college": "UCF",
    "birthPlace": "Rochester, NY, USA",
    "experience": 8,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/2284331/emma-cannon",
    "ppg": 0.0,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/2284331.png"
  },
  {
    "id": "4565515",
    "name": "Tonie Morgan",
    "team": "Los Angeles Sparks",
    "position": "Player",
    "jersey": "4",
    "age": 22,
    "height": "5' 9\"",
    "college": "Kentucky",
    "birthPlace": "Tallahassee, FL, USA",
    "experience": 0,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/4565515/tonie-morgan",
    "ppg": 0.0,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/4565515.png"
  },
  {
    "id": "4597509",
    "name": "Aaliyah Nye",
    "team": "Los Angeles Sparks",
    "position": "Player",
    "jersey": "32",
    "age": 24,
    "height": "6' 0\"",
    "college": "Alabama",
    "birthPlace": "East Lansing, MI, USA",
    "experience": 2,
    "status": "Out",
    "profile": "https://www.espn.com/wnba/player/_/id/4597509/aaliyah-nye",
    "ppg": 0.0,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/4597509.png"
  },
  {
    "id": "4280877",
    "name": "Chloe Bibby",
    "team": "Minnesota Lynx",
    "position": "Player",
    "jersey": "55",
    "age": 28,
    "height": "6' 2\"",
    "college": "Maryland",
    "birthPlace": "Warracknabeal, VIC, Australia",
    "experience": 2,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/4280877/chloe-bibby",
    "ppg": 0.0,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/4280877.png"
  },
  {
    "id": "5208984",
    "name": "Elena Buenavida",
    "team": "Minnesota Lynx",
    "position": "Player",
    "jersey": "",
    "age": 22,
    "height": "5' 9\"",
    "college": "",
    "birthPlace": "",
    "experience": 0,
    "status": "Out",
    "profile": "https://www.espn.com/wnba/player/_/id/5208984/elena-buenavida",
    "ppg": 0.0,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/5208984.png"
  },
  {
    "id": "3917450",
    "name": "Napheesa Collier",
    "team": "Minnesota Lynx",
    "position": "Player",
    "jersey": "24",
    "age": 29,
    "height": "6' 1\"",
    "college": "UConn",
    "birthPlace": "O' Fallon, MO, USA",
    "experience": 8,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/3917450/napheesa-collier",
    "ppg": 0.0,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/3917450.png"
  },
  {
    "id": "5345478",
    "name": "Eliska Joklova",
    "team": "Minnesota Lynx",
    "position": "Player",
    "jersey": "11",
    "age": 24,
    "height": "5' 11\"",
    "college": "",
    "birthPlace": "",
    "experience": 0,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/5345478/eliska-joklova",
    "ppg": 0.0,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/5345478.png"
  },
  {
    "id": "4398938",
    "name": "Dorka Juhasz",
    "team": "Minnesota Lynx",
    "position": "Player",
    "jersey": "14",
    "age": 26,
    "height": "6' 5\"",
    "college": "UConn",
    "birthPlace": "Pecs, Hungary",
    "experience": 3,
    "status": "Out",
    "profile": "https://www.espn.com/wnba/player/_/id/4398938/dorka-juhasz",
    "ppg": 0.0,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/4398938.png"
  },
  {
    "id": "4596309",
    "name": "Liatu King",
    "team": "Minnesota Lynx",
    "position": "Player",
    "jersey": "2",
    "age": 24,
    "height": "5' 11\"",
    "college": "Notre Dame",
    "birthPlace": "Washington, DC, USA",
    "experience": 2,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/4596309/liatu-king",
    "ppg": 0.0,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/4596309.png"
  },
  {
    "id": "3102133",
    "name": "Rebecca Allen",
    "team": "New York Liberty",
    "position": "Player",
    "jersey": "9",
    "age": 33,
    "height": "6' 2\"",
    "college": "",
    "birthPlace": "Wangaratta, VIC, Australia",
    "experience": 11,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/3102133/rebecca-allen",
    "ppg": 0.0,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/3102133.png"
  },
  {
    "id": "4398589",
    "name": "Elizabeth Balogun",
    "team": "New York Liberty",
    "position": "Player",
    "jersey": "5",
    "age": 25,
    "height": "6' 2\"",
    "college": "Duke",
    "birthPlace": "Lagos, Nigeria",
    "experience": 0,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/4398589/elizabeth-balogun",
    "ppg": 0.0,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/4398589.png"
  },
  {
    "id": "4790258",
    "name": "Raquel Carrera",
    "team": "New York Liberty",
    "position": "Player",
    "jersey": "14",
    "age": 24,
    "height": "6' 3\"",
    "college": "",
    "birthPlace": "",
    "experience": 0,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/4790258/raquel-carrera",
    "ppg": 0.0,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/4790258.png"
  },
  {
    "id": "4790260",
    "name": "Marine Fauthoux",
    "team": "New York Liberty",
    "position": "Player",
    "jersey": "4",
    "age": 25,
    "height": "5' 9\"",
    "college": "",
    "birthPlace": "",
    "experience": 0,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/4790260/marine-fauthoux",
    "ppg": 0.0,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/4790260.png"
  },
  {
    "id": "4683006",
    "name": "Leonie Fiebich",
    "team": "New York Liberty",
    "position": "Player",
    "jersey": "13",
    "age": 26,
    "height": "6' 4\"",
    "college": "",
    "birthPlace": "Landsberg am Lech, Germany",
    "experience": 3,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/4683006/leonie-fiebich",
    "ppg": 0.0,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/4683006.png"
  },
  {
    "id": "4066533",
    "name": "Sabrina Ionescu",
    "team": "New York Liberty",
    "position": "Player",
    "jersey": "20",
    "age": 28,
    "height": "5' 11\"",
    "college": "Oregon",
    "birthPlace": "Walnut Creek, CA, USA",
    "experience": 7,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/4066533/sabrina-ionescu",
    "ppg": 0.0,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/4066533.png"
  },
  {
    "id": "4281930",
    "name": "Anneli Maley",
    "team": "New York Liberty",
    "position": "Player",
    "jersey": "24",
    "age": 28,
    "height": "6' 1\"",
    "college": "TCU",
    "birthPlace": "Melbourne, VIC, Australia",
    "experience": 2,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/4281930/anneli-maley",
    "ppg": 0.0,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/4281930.png"
  },
  {
    "id": "4281929",
    "name": "Satou Sabally",
    "team": "New York Liberty",
    "position": "Player",
    "jersey": "0",
    "age": 28,
    "height": "6' 4\"",
    "college": "Oregon",
    "birthPlace": "Berlin, Germany",
    "experience": 7,
    "status": "Out",
    "profile": "https://www.espn.com/wnba/player/_/id/4281929/satou-sabally",
    "ppg": 0.0,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/4281929.png"
  },
  {
    "id": "4688629",
    "name": "Shay Ciezki",
    "team": "Phoenix Mercury",
    "position": "Player",
    "jersey": "5",
    "age": 22,
    "height": "5' 7\"",
    "college": "Indiana",
    "birthPlace": "Buffalo, NY, USA",
    "experience": 0,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/4688629/shay-ciezki",
    "ppg": 0.0,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/4688629.png"
  },
  {
    "id": "4698730",
    "name": "Kara Dunn",
    "team": "Phoenix Mercury",
    "position": "Player",
    "jersey": "12",
    "age": 22,
    "height": "5' 11\"",
    "college": "USC",
    "birthPlace": "Dallas, GA, USA",
    "experience": 0,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/4698730/kara-dunn",
    "ppg": 0.0,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/4698730.png"
  },
  {
    "id": "4873359",
    "name": "Kyara Linskens",
    "team": "Phoenix Mercury",
    "position": "Player",
    "jersey": "31",
    "age": 29,
    "height": "6' 4\"",
    "college": "",
    "birthPlace": "",
    "experience": 2,
    "status": "Out",
    "profile": "https://www.espn.com/wnba/player/_/id/4873359/kyara-linskens",
    "ppg": 0.0,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/4873359.png"
  },
  {
    "id": "3906769",
    "name": "Jovana Nogic",
    "team": "Phoenix Mercury",
    "position": "Player",
    "jersey": "29",
    "age": 28,
    "height": "6' 0\"",
    "college": "Providence",
    "birthPlace": "Belgrade, Serbia",
    "experience": 0,
    "status": "Out",
    "profile": "https://www.espn.com/wnba/player/_/id/3906769/jovana-nogic",
    "ppg": 0.0,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/3906769.png"
  },
  {
    "id": "3065570",
    "name": "Kelsey Plum",
    "team": "Phoenix Mercury",
    "position": "Player",
    "jersey": "0",
    "age": 32,
    "height": "5' 8\"",
    "college": "Washington",
    "birthPlace": "Poway, CA, USA",
    "experience": 9,
    "status": "Out",
    "profile": "https://www.espn.com/wnba/player/_/id/3065570/kelsey-plum",
    "ppg": 0.0,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/3065570.png"
  },
  {
    "id": "4704594",
    "name": "Marta Suarez",
    "team": "Phoenix Mercury",
    "position": "Player",
    "jersey": "77",
    "age": 24,
    "height": "6' 3\"",
    "college": "TCU",
    "birthPlace": "Oviedo, Spain",
    "experience": 0,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/4704594/marta-suarez",
    "ppg": 0.0,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/4704594.png"
  },
  {
    "id": "4433424",
    "name": "Maddy Westbeld",
    "team": "Phoenix Mercury",
    "position": "Player",
    "jersey": "21",
    "age": 24,
    "height": "6' 3\"",
    "college": "Notre Dame",
    "birthPlace": "Kettering, OH, USA",
    "experience": 2,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/4433424/maddy-westbeld",
    "ppg": 0.0,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/4433424.png"
  },
  {
    "id": "887",
    "name": "Sami Whitcomb",
    "team": "Phoenix Mercury",
    "position": "Player",
    "jersey": "33",
    "age": 38,
    "height": "5' 10\"",
    "college": "Washington",
    "birthPlace": "Ventura, CA, USA",
    "experience": 10,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/887/sami-whitcomb",
    "ppg": 0.0,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/887.png"
  },
  {
    "id": "4703794",
    "name": "Sarah Ashlee Barker",
    "team": "Portland Fire",
    "position": "Player",
    "jersey": "3",
    "age": 24,
    "height": "6' 0\"",
    "college": "Alabama",
    "birthPlace": "Birmingham, AL, USA",
    "experience": 2,
    "status": "Out",
    "profile": "https://www.espn.com/wnba/player/_/id/4703794/sarah-ashlee-barker",
    "ppg": 0.0,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/4703794.png"
  },
  {
    "id": "4433795",
    "name": "Sania Feagin",
    "team": "Portland Fire",
    "position": "Player",
    "jersey": "1",
    "age": 23,
    "height": "6' 3\"",
    "college": "South Carolina",
    "birthPlace": "Ellenwood, GA, USA",
    "experience": 2,
    "status": "Out",
    "profile": "https://www.espn.com/wnba/player/_/id/4433795/sania-feagin",
    "ppg": 0.0,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/4433795.png"
  },
  {
    "id": "4682797",
    "name": "Luisa Geiselsoder",
    "team": "Portland Fire",
    "position": "Player",
    "jersey": "15",
    "age": 26,
    "height": "6' 4\"",
    "college": "",
    "birthPlace": "Ansbach, Germany",
    "experience": 2,
    "status": "Out",
    "profile": "https://www.espn.com/wnba/player/_/id/4682797/luisa-geiselsoder",
    "ppg": 0.0,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/4682797.png"
  },
  {
    "id": "5108051",
    "name": "Jordan Harrison",
    "team": "Portland Fire",
    "position": "Player",
    "jersey": "2",
    "age": 22,
    "height": "5' 6\"",
    "college": "West Virginia",
    "birthPlace": "Oklahoma City, OK, USA",
    "experience": 0,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/5108051/jordan-harrison",
    "ppg": 0.0,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/5108051.png"
  },
  {
    "id": "3142242",
    "name": "Amy Okonkwo",
    "team": "Portland Fire",
    "position": "Player",
    "jersey": "8",
    "age": 30,
    "height": "6' 2\"",
    "college": "TCU",
    "birthPlace": "Rancho Cucamonga, CA, USA",
    "experience": 1,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/3142242/amy-okonkwo",
    "ppg": 0.0,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/3142242.png"
  },
  {
    "id": "4433690",
    "name": "Holly Winterburn",
    "team": "Portland Fire",
    "position": "Player",
    "jersey": "77",
    "age": 25,
    "height": "5' 11\"",
    "college": "Oregon",
    "birthPlace": "Northampton, England",
    "experience": 0,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/4433690/holly-winterburn",
    "ppg": 0.0,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/4433690.png"
  },
  {
    "id": "4433643",
    "name": "Mackenzie Holmes",
    "team": "Seattle Storm",
    "position": "Player",
    "jersey": "54",
    "age": 25,
    "height": "6' 3\"",
    "college": "Indiana",
    "birthPlace": "Gorham, ME, USA",
    "experience": 2,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/4433643/mackenzie-holmes",
    "ppg": 0.0,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/4433643.png"
  },
  {
    "id": "4420318",
    "name": "Ezi Magbegor",
    "team": "Seattle Storm",
    "position": "Player",
    "jersey": "13",
    "age": 27,
    "height": "6' 4\"",
    "college": "",
    "birthPlace": "Wellington, New Zealand",
    "experience": 7,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/4420318/ezi-magbegor",
    "ppg": 0.0,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/4420318.png"
  },
  {
    "id": "5106222",
    "name": "Taina Mair",
    "team": "Seattle Storm",
    "position": "Player",
    "jersey": "22",
    "age": 22,
    "height": "5' 9\"",
    "college": "Duke",
    "birthPlace": "Boston, MA, USA",
    "experience": 0,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/5106222/taina-mair",
    "ppg": 0.0,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/5106222.png"
  },
  {
    "id": "4898400",
    "name": "Taylor Thierry",
    "team": "Seattle Storm",
    "position": "Player",
    "jersey": "3",
    "age": 23,
    "height": "6' 1\"",
    "college": "Ohio State",
    "birthPlace": "Cleveland, OH, USA",
    "experience": 2,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/4898400/taylor-thierry",
    "ppg": 0.0,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/4898400.png"
  },
  {
    "id": "5364343",
    "name": "Ornella Bankole",
    "team": "Toronto Tempo",
    "position": "Player",
    "jersey": "33",
    "age": 28,
    "height": "5' 11\"",
    "college": "",
    "birthPlace": "Auxerre, France",
    "experience": 0,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/5364343/ornella-bankole",
    "ppg": 0.0,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/5364343.png"
  },
  {
    "id": "2569044",
    "name": "Temi Fagbenle",
    "team": "Toronto Tempo",
    "position": "Player",
    "jersey": "14",
    "age": 33,
    "height": "6' 5\"",
    "college": "USC",
    "birthPlace": "London, England",
    "experience": 6,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/2569044/temi-fagbenle",
    "ppg": 0.0,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/2569044.png"
  },
  {
    "id": "4398766",
    "name": "Zaay Green",
    "team": "Toronto Tempo",
    "position": "Player",
    "jersey": "00",
    "age": 26,
    "height": "6' 2\"",
    "college": "Alabama",
    "birthPlace": "Duncanville, TX, USA",
    "experience": 0,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/4398766/zaay-green",
    "ppg": 0.0,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/4398766.png"
  },
  {
    "id": "4684384",
    "name": "Aneesah Morrow",
    "team": "Toronto Tempo",
    "position": "Player",
    "jersey": "24",
    "age": 23,
    "height": "6' 1\"",
    "college": "LSU",
    "birthPlace": "Chicago, IL, USA",
    "experience": 2,
    "status": "Out",
    "profile": "https://www.espn.com/wnba/player/_/id/4684384/aneesah-morrow",
    "ppg": 0.0,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/4684384.png"
  },
  {
    "id": "4565505",
    "name": "Kiki Rice",
    "team": "Toronto Tempo",
    "position": "Player",
    "jersey": "1",
    "age": 22,
    "height": "5' 11\"",
    "college": "UCLA",
    "birthPlace": "Bethesda, MD, USA",
    "experience": 0,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/4565505/kiki-rice",
    "ppg": 0.0,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/4565505.png"
  },
  {
    "id": "4398768",
    "name": "Nyara Sabally",
    "team": "Toronto Tempo",
    "position": "Player",
    "jersey": "8",
    "age": 26,
    "height": "6' 5\"",
    "college": "Oregon",
    "birthPlace": "Berlin, Germany",
    "experience": 4,
    "status": "Out",
    "profile": "https://www.espn.com/wnba/player/_/id/4398768/nyara-sabally",
    "ppg": 0.0,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/4398768.png"
  },
  {
    "id": "2988756",
    "name": "Brittney Sykes",
    "team": "Toronto Tempo",
    "position": "Player",
    "jersey": "20",
    "age": 32,
    "height": "5' 11\"",
    "college": "Syracuse",
    "birthPlace": "Newark, NJ, USA",
    "experience": 10,
    "status": "Out",
    "profile": "https://www.espn.com/wnba/player/_/id/2988756/brittney-sykes",
    "ppg": 0.0,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/2988756.png"
  },
  {
    "id": "4433523",
    "name": "Rori Harmon",
    "team": "Washington Mystics",
    "position": "Player",
    "jersey": "3",
    "age": 23,
    "height": "5' 6\"",
    "college": "Texas",
    "birthPlace": "Houston, TX, USA",
    "experience": 0,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/4433523/rori-harmon",
    "ppg": 0.0,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/4433523.png"
  },
  {
    "id": "2593770",
    "name": "Betnijah Laney-Hamilton",
    "team": "Washington Mystics",
    "position": "Player",
    "jersey": "4",
    "age": 32,
    "height": "6' 0\"",
    "college": "Rutgers",
    "birthPlace": "Clayton, DE, USA",
    "experience": 10,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/2593770/betnijah-laney-hamilton",
    "ppg": 0.0,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/2593770.png"
  },
  {
    "id": "5106145",
    "name": "Darianna Littlepage-Buggs",
    "team": "Washington Mystics",
    "position": "Player",
    "jersey": "5",
    "age": 22,
    "height": "6' 1\"",
    "college": "Baylor",
    "birthPlace": "Oklahoma City, OK, USA",
    "experience": 0,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/5106145/darianna-littlepage-buggs",
    "ppg": 0.0,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/5106145.png"
  },
  {
    "id": "4433815",
    "name": "Lucy Olsen",
    "team": "Washington Mystics",
    "position": "Player",
    "jersey": "33",
    "age": 23,
    "height": "5' 10\"",
    "college": "Iowa",
    "birthPlace": "Collegeville, PA, USA",
    "experience": 2,
    "status": "Active",
    "profile": "https://www.espn.com/wnba/player/_/id/4433815/lucy-olsen",
    "ppg": 0.0,
    "headshot": "https://a.espncdn.com/i/headshots/wnba/players/full/4433815.png"
  }
];
